### ISSUE TITLE
Can you lower the min SDK?

### ISSUE THREAD

**Issue by Buckstabue** [getbouncer/cardscan-android#119]
Our android application min sdk is 19, while this lib requires at least 21. Is it possible to lower the min sdk?

**Comment by kingst** [comment]
We just recently updated this so as a short term fix you can use version `1.0.5139` which still has a min sdk of 19, but we'll bump this thread when we have a more concrete answer about the future of our SDK version.

**Comment by awushensky** [comment]
Hi @Buckstabue , we've released version 1.0.5143, which reduces the min sdk version to 19.

I'm going to close this issue as resolved. Please re-open if you encounter an issue with this build.
