### ISSUE TITLE
Analyzer failure with DexGuard enabled

### ISSUE THREAD

**Issue by fondesa** [getbouncer/cardscan-android#202]
When DexGuard is enabled, as soon as a `CardScanActivity` is opened and the camera permissions are accepted, the activity closes itself automatically invoking `CardScanActivityResultHandler.analyzerFailure()`.

Adding the following rule fixes the problem:
```
-keep class org.tensorflow.lite.Interpreter { *; }
```

Important notes:
- Everything works correctly if DexGuard is disabled
- It does not depend on the API key
- It fails on all the devices
- I believe it could fail also using ProGuard, since the rule isn't strictly related to DexGuard but it's a ProGuard rule

--------
**SDK version**: 2.0.0020

**Comment by awushensky** [comment]
Thanks for the report @fondesa ! I've added your suggestion to our proguard rules files and have released version 2.0.0029 which includes the new proguard rules. Please let me know if anything else needs to change.
