### ISSUE TITLE
Not getting expiryMonth and expiryYear after scan

### ISSUE THREAD

**Issue by TestShaligram** [getbouncer/cardscan-android#29]
When I scan my card in iOS it scans card number, expiry month and expiry year but in android, when I scan the same card it only scans card number. I am not getting expiry month and expiry year.
Here it is my code:

```
private void scanCard() {
        ScanActivity.start(this); 
}
@Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (ScanActivity.isScanResult(requestCode)) {
            if (resultCode == ScanActivity.RESULT_OK && data != null) {
                CreditCard scanResult = ScanActivity.creditCardFromResult(data);
                if (scanResult != null) {
                    Log.e("expiryMonth", scanResult.expiryMonth);
                    Log.e("expiryYear", scanResult.expiryYear);
                    Log.e("number", scanResult.number);
                }
            }
        }
    }
```

**Comment by kingst** [comment]
When you scan it on Android does the expiration date appear in white? You can see what I'm talking about in this [gif](https://raw.githubusercontent.com/getbouncer/cardscan-android/master/card_scan.gif). In other words, is the issue that the library detects the expiration date but isn't surfacing it appropriately or that it isn't picking it up at all?

**Comment by TestShaligram** [comment]
It isn't picking at all.

**Comment by TestShaligram** [comment]
Sorry, but there was an issue in a card(there were scratches on the card on valid thru), by changing card it is working now :)

**Comment by iKhan1057** [comment]
For Android:
 I have tested various cards, but **expiry date** is not getting detected at all.
To help none of the cards have scratch.

Card Number detection is perfect.
