### ISSUE TITLE
Mention new introduced strings in changelog and docs.

### ISSUE THREAD

**Issue by francescocervone** [getbouncer/cardscan-android#291]
`bouncer_processing_card` string resource has been added in `2.0.0049` release, but it wasn't mentioned in your [changelog](https://github.com/getbouncer/cardscan-android/blob/master/CHANGELOG.md) nor in your [documentation](https://docs.getbouncer.com/card-scan/android-integration-guide/ui-customization-guide#text-and-localization).

It's not easy for clients making sure that all string resources are customized, especially if the library declares them in multiple modules (`scan-ui` and `cardscan-ui`).

**Comment by awushensky** [comment]
@francescocervone Apologies! I'll try to be more rigorous about this process going forward

**Comment by awushensky** [comment]
I have added that string to our documentation. Going forward, I'll be checking any PRs for new strings and adding them there and in the changelog.

**Comment by francescocervone** [comment]
Thanks!
