### ISSUE TITLE
Camera is stretched vertically making the card unscannable.

### ISSUE THREAD

**Issue by arbitur** [getbouncer/cardscan-android#33]
Device: Samsung Galaxy S4
OS: Android 21
CardScan version: 1.0.5001

The gray piece is the same size of a normal visa credit card, its just a template so I dont leak sensitive information.

![Screenshot_2019-08-21-11-24-12](https://user-images.githubusercontent.com/1361280/63421230-831cdc80-c408-11e9-8ed0-496a24382d48.png)

**Comment by kingst** [comment]
We have a Note 3 that is from the same era as the s4, let me take a look at it today to see if I can reproduce this.

**Comment by arbitur** [comment]
@kingst Whats the status?

**Comment by kingst** [comment]
The Note 3 worked fine and I've been looking through our data and I can't seem to find any data on the S4, so I don't think it's that popular of a phone anymore. I will say that the GPU on an S4 is likely to struggle with our machine learning model so it might take a long time, but it's also true that the aspect ratio needs to be right or else or model doesn't work.

**Comment by kingst** [comment]
We just made a number of changes that should fix this. You'll still see a bit of distortion in the cards on your S4 but it doesn't affect the machine learning pipeline which uses the video (the on screen content is just a preview). The version that should be better is `1.0.5102`, let me know if it's better.
