### ISSUE TITLE
screen appears weird !!! xiaomi note 7

### ISSUE THREAD

**Issue by magedsoham** [getbouncer/cardscan-android#35]
![WhatsApp Image 2019-09-26 at 10 24 40](https://user-images.githubusercontent.com/29300764/65671663-eb825d80-e047-11e9-9e53-7673a7068512.jpeg)

**Comment by Abdelrhman22** [comment]
I have the Same issue .

**Comment by kingst** [comment]
@Abdelrhman22 do you also have a Xiaomi 7 or is this on another device?

**Comment by kingst** [comment]
I just picked up one of these devices myself, we'll see if I can reproduce this bug when it arrives.

**Comment by kingst** [comment]
Looks like this is a duplicate of #31 I'm going to close this one and consolidate the discussion there. Note: I'm still pretty new to Github, let me know if this isn't the typical protocol.

**Comment by Abdelrhman22** [comment]
We are working on the same project , let me keep in contact with you
