### ISSUE TITLE
Some card scans reversed

### ISSUE THREAD

**Issue by elijahfreestone** [getbouncer/cardscan-android#388]
Hello, I'm seeing an intermittent issue where sets of numbers on some debit card scans are getting reversed, so card 1234 5678 9101 2345 is read as 2345 9101 5678 1234. Sometimes this is the initial read, while others the card number displayed in the viewfinder will update during processing. I've been able to reproduce this most often seen with a PayPal debit card that has a darker blue background and silvery numbers printed on the back. The easiest way to repro the issue seems to be to launch the scanner view while the card is fairly close to the lens, and then moving the card out to focus. Bringing the card into view pretty close also works though. I first spotted the issue while using version 2.0.0084, but am still seeing it after updating to 2.0.0088 and 2.0.0090.

Devices reproduced on:
Samsung S10 (SM-G973U1) on 11
LG G8 (LM-G820) on 10

Other devices tested without success:
Pixel XL (original) on 10
Samsung S9 (SM-G960U1) on 9

Please let me know what other information may be of use. I'm not sure how widespread the issue is at the moment, but any help would be much appreciated.

Thanks and have a great day! 
Eli

**Comment by awushensky-stripe** [comment]
Thanks so much for the report @elijahfreestone ! This is definitely a new one, I'll see if I can reproduce given the test devices I have and get an answer & fix for you.

**Comment by awushensky-stripe** [comment]
@elijahfreestone are you using the `-minimal` ocr module or the standard ocr module in your Android app? This will help me narrow my focus.

**Comment by elijahfreestone** [comment]
Hey @awushensky-stripe , we're using the `-minimal`

**Comment by awushensky-stripe** [comment]
Thanks for clarifying. @henry2304 is helping me look into this.

**Comment by awushensky-stripe** [comment]
Thanks again for the report! The fix for this bug has been released as part of version `2.1.0001`.

**Comment by elijahfreestone** [comment]
Wonderful, thank you much!!
