### ISSUE TITLE
Missing dependency on Maven Central updating to 2.1.0003

### ISSUE THREAD

**Issue by fondesa** [getbouncer/cardscan-android#407]
We are using the following dependencies:
```gradle
implementation "com.getbouncer:scan-payment-card-detect:2.0.0090"
implementation "com.getbouncer:scan-payment-ocr:2.0.0090"
implementation "com.getbouncer:tensorflow-lite:2.0.0090"
implementation "com.getbouncer:cardscan-ui:2.0.0090"
```

How can we include the minimal models in the update **2.1.0003**?

Following the [documentation](https://docs.getbouncer.com/bouncer-scan/credit-card-ocr/android-integration-guide#full-models), we should use the following dependencies:

```gradle
implementation "com.getbouncer:scan-payment-minimal:2.1.0003"
implementation "com.getbouncer:tensorflow-lite:2.1.0003"
implementation "com.getbouncer:cardscan-ui:2.1.0003"
```

But, the dependency `scan-payment-minimal` apparently isn't on [Maven Central](https://repo1.maven.org/maven2/com/getbouncer/).

**Comment by awushensky-stripe** [comment]
My apologies for the slow response, I was out on vacation and didn't see this! Thanks for pointing out the error. These were mistakenly released to maven with the wrong artifact name. I'll correct this immediately and release as part of 2.1.0004.

**Comment by awushensky-stripe** [comment]
This has been merged and is [releasing now](https://github.com/getbouncer/cardscan-android/releases/tag/2.1.0004). It will go out as part of 2.1.0004.
