### ISSUE TITLE
Getbouncer console not accessible.

### ISSUE THREAD

**Issue by iamrealkaustubh** [getbouncer/cardscan-android#487]

**Comment by awush-stripe** [comment]
Hi @iamrealkaustubh ,

As we continue to migrate into Stripe’s ecosystem, we deprecated the bouncer console (http://api.getbouncer.com/console) on February 8, 2022 - If you would like access to your API keys, please email [bouncer-support@stripe.com](mailto:bouncer-support@stripe.com).

Going forward, new signups will use the new [Stripe SDK](https://github.com/stripe/stripe-android/tree/master/stripecardscan), which is nearing first release.

Please reach out with any questions.
