### ISSUE TITLE
The new CardScanSheet API doesn't deliver result when starter activity is destroyed

### ISSUE THREAD

**Issue by francescocervone** [getbouncer/cardscan-android#491]
The new "not-yet-documented" `CardScanSheet` API (https://github.com/getbouncer/cardscan-android/issues/486) does not work correctly when the starter activity is destroyed due to low memory conditions.

The API registers the result callback in the [`CardScanSheet.present`](https://github.com/getbouncer/cardscan-android/blob/master/cardscan-ui/src/main/java/com/getbouncer/cardscan/ui/CardScanSheet.kt#L147) method, but when the card scan activity is started, the caller activity could be destroyed, losing the reference to the `CardScanSheet` object. 

Even if you recreate the CardScanSheet with `CardScanSheet.create` in `Activity.onCreate` method, you cannot register the result callback without presenting the screen (`CardScanSheet.present`).

# Solution
The `CardScanSheet` API should be declared like this

```kotlin
fun create(from: ComponentActivity, apiKey: String, onFinished: (CardScanSheetResult) -> Unit)
fun create(from: Fragment, apiKey: String, onFinished: (CardScanSheetResult) -> Unit)
fun present(
  enableEnterManually: Boolean,
  enableNameExtraction: Boolean,
  enableExpiryExtraction: Boolean
)
```

So that the result callback is registered in `onCreate` and is consistent with the activity result API.

# Steps to reproduce
1) Open device's `Settings > System > Developer's Options`
2) Enable `Don't keep activities` flag
3) Open an app with the card scan integration
4) Scan a card
5) Result is not dispatched.

**Comment by awush-stripe** [comment]
Great callout. Thank you for the report! I'll address this ASAP.
