### ISSUE TITLE
Can't scan Card Starts with "50" 

### ISSUE THREAD

**Issue by magedsoham** [getbouncer/cardscan-android#66]
We have a new card Called meeza in Egypt which it's number starts with "50"
we can't scan it
could you please add this network type to your code ASAP

**Comment by magedsoham** [comment]
can't scan also card starts with "527803"

**Comment by awushensky** [comment]
Thanks for pointing this out. I've filed a ticket to address this. We'll probably do something similar to what Stipe does: https://github.com/stripe/stripe-ios/blob/master/Stripe/STPBINRange.m

**Comment by awushensky** [comment]
https://github.com/getbouncer/cardscan-android/pull/72

**Comment by awushensky** [comment]
fix has been released as https://github.com/getbouncer/cardscan-android/releases/tag/1.0.5119
