### ISSUE TITLE
Show Enter card Manual

### ISSUE THREAD

**Issue by Zennaxxtech** [getbouncer/cardscan-android#77]
I have checked same version in iOS and its provide the facility that **Enter Card manual** label in bottom same as below image
![8611842B-52AC-44CC-A97E-15FAEAAC0D19](https://user-images.githubusercontent.com/35910585/71415790-8e686900-2683-11ea-9390-ac4f5257e536.jpg)
 but in android I am unable to set that label. Please let me know how to set that type of label in android also and get its onClick event. Help would be very appreciate. Thanks.

**Comment by kingst** [comment]
What do you think @awushensky ?

**Comment by awushensky** [comment]
Thanks for pointing this out. @xsl will take a look at it.

**Comment by Zennaxxtech** [comment]
I know might be take long time but let me know approx time.

**Comment by awushensky** [comment]
I believe there is a PR out for this now. I expect this will merge in the next few days.

**Comment by xsl** [comment]
hey @Zennaxxtech, we just released a change that will allow you to toggle this via an intent. 

See the following for examples:

https://github.com/getbouncer/cardscan-android/blob/master/cardscan/src/main/java/com/getbouncer/cardscan/ScanActivity.java#L69
https://github.com/getbouncer/cardscan-android/blob/master/cardscan-base/src/main/java/com/getbouncer/cardscan/base/ScanActivityImpl.java#L27

**Comment by Zennaxxtech** [comment]
Thank you so much for this solution. I have taken latest pull and try to open ScanActivity as you explained above but there is not any [this type of line](intent.putExtra(ScanActivityImpl.SHOW_ENTER_CARD_MANUALLY_BUTTON, showEnterCardNumberManually);) in the ScanActivity class. I have tried in another project also but same issue. So please let me know still its not merged or I am doing something wrong.

**Comment by awushensky** [comment]
Hi @Zennaxxtech , to clarify, you should now be able to call `ScanActivity.start(this, true, true)` to show the enter card manually button. You should not need to specifically modify any intents.

If you're using `jcenter` to include cardscan in your app, you'll need to update your version to `1.0.5123` to see these changes.

**Comment by Zennaxxtech** [comment]
Hi @awushensky , I am able to get the `Enter card manually` option's on Scanning Activity. Thank you so much.
There is one another confusion and if you can give suggestion then please let me know that how can I differentiate that user is pressed `Close` button or `Enter card Manually` button in `onActivityResult()` method?

**Comment by awushensky** [comment]
Absolutely. The intent passed to `onActivityResult()` will have an extra value `"result_enter_card_manually"` set to `true` if the user tapped that button.

See this line for details:
https://github.com/getbouncer/cardscan-android/blob/master/cardscan-base/src/main/java/com/getbouncer/cardscan/base/ScanBaseActivity.java#L535
