### ISSUE TITLE
Modify access levels in "Overlay.java" class 

### ISSUE THREAD

**Issue by mahmoudjafarinejad** [getbouncer/cardscan-android#88]
Hi! We are trying to use the library by adding the dependency, however, we need to customize the overlay class so we could have our own overlay. Is it possible for you to change the access levels of the methods and parameters in the "Overlay.java" class from "private" to "protected"? This way we can have our own overlay which extends yours.

**Comment by awushensky** [comment]
Thanks for reporting @mahmoudjafarinejad ! this has been included in 1.0.5127
