### ISSUE TITLE
Crash on android 5 Lenovo

### ISSUE THREAD

**Issue by Olexiy98** [getbouncer/cardscan-android#89]
I don't have stacktrace but crash reproduced every time when open ScanActivityImpl, lib version is  1.0.5126

**Comment by awushensky** [comment]
Thank you for reporting @Olexiy98 . Do you know what model device the crash occurred on specifically?

**Comment by Olexiy98** [comment]
> Thank you for reporting @Olexiy98 . Do you know what model device the crash occurred on specifically?

Meizu m2 note

**Comment by awushensky** [comment]
Is there any way you can get a stack trace? I am attempting to get ahold of one of these phones, but it's difficult.

**Comment by awushensky** [comment]
Hi @Olexiy98 , we've updated the version of TFLite we use in the app. Please try with the latest release 2.0.0017.

Here is the original bug that was marked fixed in TFLite: https://github.com/tensorflow/tensorflow/issues/31114

**Comment by awushensky** [comment]
I'm closing this issue since I believe it has been fixed. Please feel free to re-open it if it reoccurs.
